name: Make a Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Publish Release Draft
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download macOS Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name-macos }}
          path: macOS
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name-windows }}
          path: Windows
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name-linux }}
          path: Linux
      - name: Archive Artifacts
        run: |
          zip -r macOS{.zip,}
          zip -r Windows{.zip,}
          zip -r Linux{.zip,}
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          removeArtifacts: true
          makeLatest: true
          tag: "v0.6.2"
          artifacts: "macOS.zip,Windows.zip,Linux.zip"
